### ISSUE TITLE
UI - Sign Up Bug

### ISSUE THREAD

**Issue by Sub-Xaero** [ThetaSinner/evelyn#3]
On Sign Up Page, repeatedly clicking the Sign-Up tab at the top toggles sign-on sign-up views, but repeatedly clicking sign-in does not

**Comment by ThetaSinner** [comment]
Description please, and specific to being served over docker right?

**Comment by Sub-Xaero** [comment]
Ik, Ik, clicked enter, rather than newline it submitted. 

Not specific to Docker, possibly behaviour of Foundation

**Comment by ThetaSinner** [comment]
oh okay, this is new to me. That is seriously strange

**Comment by Sub-Xaero** [comment]
This issue thing is weird, my bad. Does it do the same thing for you on the UI? Not breaking behaviour, but could be annoying unless they both do the same thing

**Comment by ThetaSinner** [comment]
it's just the ui router, signup on the logon page navigates to # which isn't found so we default back to logon?

**Comment by Sub-Xaero** [comment]
Fair enough, just noticed it behaving that way when I was play-testing the UI for aesthetic changes that I can make in downtime. I was already on the page and misclicked the button again and it toggled, so I was like hang on, that's not meant to do that. 

Ok for me to add routes to both buttons so they both do the same thing?

**Comment by ThetaSinner** [comment]
I would just remove the html that makes that a link to solve the problem, then fix things up with css
